repository:
  # See https://developer.github.com/v3/repos/#edit for all available settings.

  # The name of the repository. Changing this will rename the repository
  name: cloud-native-comnmunity-cookbook

  # A short description of the repository that will show up on GitHub
  description: 🍳  A collection of recipes from around the globe, submitted by members of the cloud native community.

  # A URL with more information about the repository
  homepage: https://cncf.io/projects

  # Collaborators: give specific users access to this repository.
  # Note: changing this file will update the users visible in Github UI
  # see /governance/roles.md for details on write access policy
  # note that the permissions below may provide wider access than needed for
  # a specific role, and we trust these individuals to act according to their
  # role. If there are questions, please contact one of the chairs.
collaborators:
  # Maintainers
  - username: thomcrowe
    permission: admin
  - username: markyjackson-taulia
    permission: admin
  - username: jeremytanner
    permission: admin
    
    # Technical Leads


    # Triage Team
    # manage issues (edit labels, occasionally edit)
    # needs "push" permission, even though triage team should not merge PRs


    # Security Assessment Facilitator
    # merge PRs in /assesssments according to guidelines
    # triage related issues
    # JustinCappos

    # Security Reviewers
    # issues may be assigned, edited by assignee
    # merge PRs for assigned issue according to guidelines
    # JustinCappos, ultrasaurus, lumjjb


    # Meeting Facilitators
    # ultrasaurus, dshaw, pragashj, lumjjb, justincormack, izgeri, JustinCappos
